Bivek_SImpleToDoApp/Models/ErrorViewModel.cs
using System;

namespace Bivek_SImpleToDoApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bivek_SImpleToDoApp/Models/TodoIndexModel.cs
using System.Collections.Generic;

namespace Bivek_SImpleToDoApp.Models
{
    public class TodoIndexModel
    {
        public IEnumerable<TodoTaskViewModel> Tasks { get; set; }
    }
}

Bivek_SImpleToDoApp/Models/TodoTaskViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Bivek_SImpleToDoApp.Models
{
    public class TodoTaskViewModel
    {
        public int? Id { get; set; }        
        [Required]
        public string Task { get; set; }       
        [Required]
        public string TaskDate { get; set; }
        [Required]
        public string Description { get; set; }
        public bool? IsComplete { get; set; } = false;
    }
    //public class TodoTaskPostViewModel
    //{
    //    public string Task { get; set; }
    //    [Required]
    //    public string TaskDate { get; set; }
    //    [Required]
    //    public string Description { get; set; }
    //}
}

Bivek_SImpleToDoApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Bivek_SImpleToDoApp.Models;

namespace Bivek_SImpleToDoApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bivek_SImpleToDoApp/Controllers/TodoController.cs
using Bivek_SImpleToDoApp.Models;
using LibraryData;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Globalization;
using System.Linq;

namespace Bivek_SImpleToDoApp.Controllers
{
    public class TodoController : Controller
    {
        private ITodoTasks _tasks;
        public TodoController(ITodoTasks tasks)
        {
            _tasks = tasks;
        }

        public IActionResult Index()
        {
            var taskModels = _tasks.GetAllTasks();
            var taskList = taskModels
                .Select(result => new TodoTaskViewModel
                {
                    Id = result.Id,
                    Task = result.Task,
                    Description = result.Description,
                    TaskDate = result.TaskDate.ToString("MM/dd/yyyy"),
                    IsComplete = result.IsComplete
                });
            var taskListVM = new TodoIndexModel()
            {
                Tasks = taskList
            };
            return View(taskListVM);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(TodoTaskViewModel taskVM)
        {
            if (ModelState.IsValid)
            {
                //Error due to not recognizing valid date format. aba bhayo hola yo comment delete gara
                
                DateTime TaskDate = DateTime.ParseExact(taskVM.TaskDate,"MM/dd/yyyy",CultureInfo.InvariantCulture);
                TodoTask taskModel = new TodoTask()
                {                    
                    Task = taskVM.Task,
                    Description = taskVM.Description,
                    TaskDate = TaskDate
                };
                _tasks.AddTask(taskModel);
                return RedirectToAction("Index");
            }
            else
            {
                return View(new TodoTaskViewModel());
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var taskToEdit = _tasks.GetTaskByID(id);
            string TaskDate = taskToEdit.TaskDate.ToString("MM/dd/yyyy");
            TodoTaskViewModel taskModel = new TodoTaskViewModel()
            {
                Task = taskToEdit.Task,
                Description = taskToEdit.Description,
                TaskDate = TaskDate
            };
            return View(taskModel);
        }

        [HttpPost]
        public IActionResult Edit(TodoTaskViewModel taskVM)
        {
            if (ModelState.IsValid)
            {
                if (taskVM != null)
                {
                    DateTime TaskDate = DateTime.Parse(taskVM.TaskDate);
                    TodoTask taskModel = new TodoTask()
                    {
                        Id = (int)taskVM.Id,
                        Task = taskVM.Task,
                        Description = taskVM.Description,
                        TaskDate = TaskDate
                    };
                    _tasks.UpdateTask(taskModel);
                }
                return RedirectToAction("Index");
            }
            else
            {
                return View(new TodoTaskViewModel());
            }
        }
        public IActionResult SetComplete(int id)
        {
            _tasks.SetTaskComplete(id);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteTask(int id)
        {
            _tasks.DeleteTask(id);
            return RedirectToAction("Index");
        }
    }
}

Bivek_SImpleToDoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Bivek_SImpleToDoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bivek_SImpleToDoApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bivek_SImpleToDoApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Bivek_SImpleToDoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.css" rel="stylesheet" />
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.js" type="text/javascript"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Bivek_SImpleToDoApp/Views/Todo/Create.cshtml
@model Bivek_SImpleToDoApp.Models.TodoTaskViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TodoTaskViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <input asp-for="Id" class="form-control" type="hidden" />
            </div>*@
            <div class="form-group">
                <label asp-for="Task" class="control-label"></label>
                <input asp-for="Task" class="form-control" />
                <span asp-validation-for="Task" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskDate" class="control-label"></label>
                <input id="taskDatePckr" asp-for="TaskDate" class="form-control" />
                <span asp-validation-for="TaskDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @*<div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsComplete" /> @Html.DisplayNameFor(model => model.IsComplete)
                    </label>
                </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>



<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
    $(document).ready(function ($) {
        $('#taskDatePckr').datepicker({
            changeMonth: true,
            changeYear: true,
            format: "MM/dd/yyyy",
            minDate:new Date()
        });
    });
</script>

Bivek_SImpleToDoApp/Views/Todo/Edit.cshtml
@model Bivek_SImpleToDoApp.Models.TodoTaskViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TodoTaskViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="Task" class="control-label"></label>
                <input asp-for="Task" class="form-control" />
                <span asp-validation-for="Task" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskDate" class="control-label"></label>
                <input id="taskDatePckr" asp-for="TaskDate" class="form-control" />
                <span asp-validation-for="TaskDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
    $(document).ready(function ($) {
        $('#taskDatePckr').datepicker({
            changeMonth: true,
            changeYear: true,
            format: "MM/dd/yyyy"
        });
    });
</script>

Bivek_SImpleToDoApp/Views/Todo/Index.cshtml
@model Bivek_SImpleToDoApp.Models.TodoIndexModel

<div id="todoTaskWrap">
    <div class="divAddNewBtn">
        <a asp-action="Create" asp-controller="Todo" class="btn btn-primary">Add New</a>
    </div>
    <div id="todoTaskList">
        <table class="table">
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Description</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Tasks)
                {
                    <tr>
                        <td>
                            @item.Task
                        </td>
                        <td>
                            @item.Description
                        </td>
                        <td>
                            @item.TaskDate
                        </td>
                        <td>
                            @if ((bool)item.IsComplete)
                            {
                                <span style="color:lawngreen;">Completed</span>
                            }
                            else
                            {
                                <span style="color:orangered;">Remaining</span>
                            }
                        </td>
                        <td>
                            @if (!(bool)item.IsComplete)
                            {
                                <a asp-action="SetComplete" asp-route-id="@item.Id " onclick="return confirm('Are you sure you want to set the task as completed?')">
                                    <i class="fa fa-check"></i>Done
                                </a>
                                <a asp-action="Edit" asp-route-id="@item.Id"><i class="fa far fa-edit"></i>Edit</a>
                            }
                                <a asp-action="DeleteTask" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to delete @item.Task ?')"><i class="fa far fa-delete"></i>Delete</a>
                            </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>